name: deploy-dev-prod
on:
  workflow_dispatch:
  
jobs:
    job1:
        name: deploy-dev
        environment: 
          name: development
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@main
            - name: Use Python version 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install az ml extension
              run: |
                python -m pip install azure-cli
                az extension add -n ml -y
            - name: login in dev-environment
              uses: azure/login@v1
              with:
                creds: ${{secrets.AZURE_CREDENTIALS_DEV}}
            - name: Trigger AzureML job in dev-environment
              run: |
                az ml job create --file src/job_deploy_dev.yml \
                --resource-group myResourcegroupforML --workspace-name learnML \
                 -n dev-deploy-job-github-${{github.run_number}}   
            - name: Check job status
              run: |
                python check_job_status.py --name dev-deploy-job-github-${{github.run_number}}
    job2:
        needs: job1
        name: deploy-prod
        environment: 
          name: production
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo
              uses: actions/checkout@main
            - name: Use Python version 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8
            - name: Install az ml extension
              run: |
                pip install azure-cli
                az extension add -n ml -y
            - name: login in dev-environment
              uses: azure/login@v1
              with:
                creds: ${{secrets.AZURE_CREDENTIALS_PROD}}
            - name: Trigger AzureML job in prod-environment
              run: |
                az ml job create --file src/job_deploy_prod.yml \
                --resource-group myResourcegroupforML --workspace-name learnML \
                 -n prod-deploy-job-github-${{github.run_number}}

      

