name: pull-triggered-job    
on:
  workflow_dispatch:
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
       echo "Will add code checks here in next challenge"